### ISSUE TITLE
Create a properties file

### ISSUE THREAD

**Issue by oconnelc** [iliterobotics/FRC-Vision#10]
We have a lot of calibration and hard-coded values in our code. We need a configuration file with all of the settings. Keep this simple, this should either be XML or just a simple key-value properties file

**Comment by danielchristopher1** [comment]
Added the properties file.

**Comment by oconnelc** [comment]
In addition to the properties file, we need a way for the code to load the properties into itself. Take a look at all of the "private static final" variables and move those values into a properties file. Test to make sure they load. Also don't push directly onto the master branch.

**Comment by danielchristopher1** [comment]
I will do that next. Currently working on the pause button.

**Comment by danielchristopher1** [comment]
Fixed in db20c99bb3d7d872ee131e35d53d548a76986dce
