### ISSUE TITLE
Use spaces instead of tabs. 

### ISSUE THREAD

**Issue by danielchristopher1** [iliterobotics/FRC-Vision#16]
Tabs are still being used rather than spaces.

**Comment by oconnelc** [comment]
Could you please include the files that are still incorrect?

**Comment by danielchristopher1** [comment]
I am actually fixing it myself. I will push it up in a minute.

**Comment by danielchristopher1** [comment]
How do I go back a commit?

**Comment by danielchristopher1** [comment]
I wasn't able to fix it. All of the files are coming up with tabs. My configurations are correct. I believe the issue is you have to do a ctrl + f to reformat it after you change from tabs to spaces. I looked it up and tried it out. That has to be the issue.
