### ISSUE TITLE
Some resources aren't being closed

### ISSUE THREAD

**Issue by danielchristopher1** [iliterobotics/FRC-Vision#23]
I noticed that exiting all of the application's windows isn't killing every thread. My camera still shines it's light until I stop the program completely through eclipse.

**Comment by oconnelc** [comment]
It looks like it's the Executor service in the LocalCamera. We should add a destroy method in the ICameraConnection and have LocalCamera call shutdown. We may even want to add a shutdown hook and set all JFrames to "Exit on close"

**Comment by danielchristopher1** [comment]
Fixed in commit 554ce92dd8df66faf760993adde670c773011c49
