### ISSUE TITLE
Create dialog to allow user to enter name of object. 

### ISSUE THREAD

**Issue by oconnelc** [iliterobotics/FRC-Vision#30]
This dialog will be used to generate the variables used to train the object detect logic. This dialog should be shown after the user releases the selection rectangle and should take a snapshot of what was selected. This dialog should show the average color and allow the user to enter the name of the object. There should be two buttons at the botom: Save and Drop. The Save button will save the average color and the name of the object to an XML file. The drop button will just dispose the dialog.

**Comment by danielchristopher1** [comment]
Fixed in commit 2c1f7c4edf7e0176875cf760dff0eae33ceec388
