### ISSUE TITLE
Small issue after switching to gradle

### ISSUE THREAD

**Issue by danielchristopher1** [iliterobotics/FRC-Vision#46]
Pull down my latest commit, I had to fix the rectangle selection again. For some reason it was messed up after we switched to gradle. I forgot to push up the latest version of it because I committed a version that I thought was working but then I realized it wasn't. I kept working, forgot, and deleted the branch thinking I was done with it. Regardless, this contains the fix.

**Comment by oconnelc** [comment]
What contains the fix? Was it one of the branches I merged in today?

**Comment by danielchristopher1** [comment]
I believe I pushed the fix right off of master. My bad. It's currently in origin master
