### ISSUE TITLE
Image Blender is failing to load the OverlayHook.png

### ISSUE THREAD

**Issue by oconnelc** [iliterobotics/FRC-Vision#82]
I'm getting the following stack trace when I try to run the ImageBlender:

Exception in thread "main" javax.imageio.IIOException: Can't read input file!
    at javax.imageio.ImageIO.read(ImageIO.java:1301)
    at org.ilite.vision.api.system.VisionSystemAPI.loadImage(VisionSystemAPI.java:30)
    at org.ilite.vision.api.system.ImageBlender.<init>(ImageBlender.java:69)
    at org.ilite.vision.api.system.ImageBlender.main(ImageBlender.java:122)

It looks like it's having problems loading the property OverlayImagePath

**Comment by danielchristopher1** [comment]
Okay. I can fix that. What do you think about the blob detection code loading in the values from json? Work properly?

**Comment by danielchristopher1** [comment]
Currently it takes the last set of blob data in the json array. I can't seem to figure out how to get it to detect every set of  hsv data in the file. Point me in a direction?

**Comment by danielchristopher1** [comment]
Check my latest commit

**Comment by oconnelc** [comment]
That fixes it, but I thought we were going to load the paths from the properties.json.

**Comment by oconnelc** [comment]
For your comment "Currently it takes the last set of blob data in the json array. I can't seem to figure out how to get it to detect every set of hsv data in the file. Point me in a direction?"

Where is this trying to use the blob data in the JSON array?

**Comment by oconnelc** [comment]
Nevermind I found it. I'm going to push up a branch with some comments in the code for suggestions. Do not merge this branch into master.

**Comment by danielchristopher1** [comment]
Ill throw it into properties, sorry. It's using it in ObjectDetectorRenderable. Check out the readBlobData()  and detectColorBlob() methods. Also, Prof Drake wants to see the image blender. When I launch it I only see the overlay, not the background image you took.

**Comment by danielchristopher1** [comment]
Sorry, I'm being stupid. never mind about the background.

**Comment by oconnelc** [comment]
The Image Blender is designed to work with the live video feed. I'll write something really quick that will overlay it onto the still frame

**Comment by oconnelc** [comment]
Also I went ahead and pushed a notes branch with how to do multiple object detect

**Comment by oconnelc** [comment]
Ok I just pushed up something for Professor Drake.

**Comment by oconnelc** [comment]
Just pull down master and run the ImageBlender. I still need to clean up the overlay image so that it does the following things:

1) The current overlay is highlighting the lower portion of the hook. I'm going to update the OverlayImage so that it doesn't have the lower portion of the hook. 
2) I still need an overlay for the lower lip of the tote.

**Comment by oconnelc** [comment]
Ok I just put up another fix for the ImageBlender. My last commit broker the alpha slider. That has been resolved. Also item 1 on my last comment has been fixed.

**Comment by danielchristopher1** [comment]
i didnt get the change where the slider works

**Comment by danielchristopher1** [comment]
i pulled but it wasnt there

**Comment by danielchristopher1** [comment]
You forgot to merge the branch, I merged it for you.

**Comment by danielchristopher1** [comment]
So try the detection code i wrote. Let me know what you think If it's good, I'll move on to multiple object detection. It will save off the values whenever you press the save button on the save dialog. After that, the file is immediatly reloaded into the program so you will get the change. You can terminate the program and re run it and it will pull from json just fine and detect what was wanted

**Comment by danielchristopher1** [comment]
What do you mean by you need an overlay for the lower lip of the tote?

**Comment by oconnelc** [comment]
Run the latest push made. It has the lower lip of the tote overlay.

**Comment by danielchristopher1** [comment]
Okay. Drake and the build team really like it. They made me change the color of the overlay to red and they said it would be better if the overlay was just an outline and wasnt completely filled

**Comment by oconnelc** [comment]
Ok push up any changes for this. I figured they'd prefer the outline, so we should be able to get that going. Once we get the overlays complete, we should add a method to the API so that they can get a reference to the Image Blender's panel. This reference should be automatically registered with the camera.

**Comment by danielchristopher1** [comment]
Okay. I am just editing this in paint, that fine?

**Comment by oconnelc** [comment]
That's what I did.

**Comment by oconnelc** [comment]
You could also use the Overlay Generator

**Comment by danielchristopher1** [comment]
Okay. I pushed up my changes.

**Comment by danielchristopher1** [comment]
They really like it. I will add a line across the top of the tote, thats what robert said to do.

**Comment by danielchristopher1** [comment]
I just pushed up my latest changes containing everything being loaded from json. All of the paths now are loaded in.

**Comment by danielchristopher1** [comment]
I have added the method

**Comment by oconnelc** [comment]
Ok did you see I did a line for the lower part of the tote?

**Comment by danielchristopher1** [comment]
yes

**Comment by danielchristopher1** [comment]
they liked it

**Comment by danielchristopher1** [comment]
So how can I get started on mutliple object detection

**Comment by danielchristopher1** [comment]
and what do you think of the detection code I wrote. Does it properly use the json values to detect?

**Comment by oconnelc** [comment]
Did you see the branch I pushed up? It's not merged into master, but it has some notes on how to proceed.

**Comment by danielchristopher1** [comment]
oh okay.

**Comment by danielchristopher1** [comment]
I think I'm done working today, I'm going to go home. I started multiple object detection. Will finish next time.
